services:
  essenvian:
    image: essenvian
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "npm install && node --inspect=0.0.0.0:9229 server.js"]
    ports:
      - 3000:3000
      - 9229:9229
